# Generated by Django 4.1.5 on 2023-01-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('content', models.CharField(max_length=1000, verbose_name='報告内容')),
                ('created_date_time', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
        ),
    ]
