# Generated by Django 4.1.5 on 2023-01-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_repo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='images')),
            ],
        ),
    ]
